### ISSUE TITLE
Jekyll parsing error

### ISSUE THREAD

**Issue by Kriesse** [OpenTechSchool/blog.opentechschool.org#1]
I tried running this locally, but I get:

"REXML could not parse this XML/HTML"
http://cl.ly/image/2e2g44463F0G

Any ideas?

**Comment by gnunicorn** [comment]
just a quick idea but officialy you have to use quotes (") not ticks (')
for xml tag attributes. Try replacing them.

**Comment by gnunicorn** [comment]
Did that fix it? Then I'd like to close this ticket ...
