### ISSUE TITLE
Make iframed embeds (e.g. from Slideshare) responsive

### ISSUE THREAD

**Issue by sjockers** [OpenTechSchool/blog.opentechschool.org#10]
At the moment, embeds from slideshare etc. are fixed width. 

It would be much better, if those would adapt to the viewport. You know, [that way](http://www.alistapart.com/articles/creating-intrinsic-ratios-for-video/).

**Comment by xMartin** [comment]
Found only one Vimeo video embed to be a problem. Fixed with https://github.com/OpenTechSchool/blog.opentechschool.org/commit/975528ee07fc5967af691b135e737b9d17953418
