### ISSUE TITLE
blog post: OpenTechSchool has impact success story

### ISSUE THREAD

**Issue by gnunicorn** [OpenTechSchool/blog.opentechschool.org#36]
Here is a really nice blogpost written by someone who attended OpenTechSchool in Berlin and is now going to become a programmer.

He says the git workshop was the most useful thing!

http://iansquare.com/blog/2013/02/21/moving-to-california/

Be sure to leave a comment on his blog to encourage him! We should also tweet the post.

**Comment by xMartin** [comment]
The site linked is down :(
