### ISSUE TITLE
How does the blog fit in the website's navigation structure?

### ISSUE THREAD

**Issue by sjockers** [OpenTechSchool/blog.opentechschool.org#5]
Currently, the blog is not referenced anywhere on the homepage and the only way to reach the homepage from the blog to click the logo in the header.

Any thoughts on that?

**Comment by Kriesse** [comment]
Yeah, that’s definitely a problem, our IA sucks right now :)
I'd say as a quick solution we should add links to all relevant OTS pages (Blog, Campus Party, Twitter, Facebook… what else?) to the footer. So the footer will serve as some sort of sitemap and at least give an overview of all OTS pages.

In the long run we'll definitely need a better navigation. Up for suggestions and discussion!

**Comment by qubodup** [comment]
Suggestion: Add "<p>We report about our events on the <a href="http://www.opentechschool.org/">OpenTechSchool Blog</a>.</p>" after "To follow what we've planned you can checkout our Meetup group and our Google calendar." on http://www.opentechschool.org/#events

**Comment by xMartin** [comment]
We now have a prominent link from the homepage to the blog. And in my opinion the logo linking back to the homepage from the blog is not perfect but sufficient.
