### ISSUE TITLE
Feed non-existent

### ISSUE THREAD

**Issue by qubodup** [OpenTechSchool/blog.opentechschool.org#7]
On http://blog.opentechschool.org/ this line exists:

```
<link href="http://feeds.feedburner.com/opentechschool" rel="alternate" title="your title" type="application/atom+xml" />
```

However, http://feeds.feedburner.com/opentechschool does not exist. Did you change the name on feed burner but forgot to change the URL on the blog?

**Comment by nekopanic** [comment]
I've created a pull request to switch to the self-hosted feed. https://github.com/OpenTechSchool/blog.opentechschool.org/pull/9

**Comment by nekopanic** [comment]
Fixed. We are hosting the atom.xml as feedburner is going to be shut down.

**Comment by qubodup** [comment]
Feedburner API indeed will be shut down: https://developers.google.com/feedburner/ (Not Feedburner itself, in case you don't use the API)
